# version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - '9092:9092'

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    environment:
      INFLUXDB_ADMIN_USER: 'admin'
      INFLUXDB_ADMIN_PASSWORD: 'adminpass'
      INFLUXDB_DB: 'marketdata'
    volumes:
      - influxdb_data:/var/lib/influxdb2
    ports:
      - '8086:8086'

  producer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: producer
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 'kafka:9092'
      KAFKA_TOPIC: 'prices'
      EXCHANGES: 'binance,kucoin,bybit'
      SYMBOLS: 'BTC/USDT,ETH/USDT,XMR/USDT'
    volumes:
      - ./:/app
    working_dir: /app
    command: ['python', 'producer.py']

volumes:
  influxdb_data:
# influx key: J4twWiQSH6QZF33ZyAB9NJLoNMyrHjOlvY6UJGgczJfk-_DC3d5BFEiZzQOYC39ObPYwxF5kZTAZtzIX-Xr40Q==
